apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
  labels:
    env: prod
    app: httpd
spec:
  replicas: 3
  selector:
    env: test
  template:
    metadata:
      labels:
        env: test
    spec:
      containers:
        - name: cont1
          image: httpd
