apiVersion: v1
kind: Pod
metadata:
  name: cmappod
spec:
  containers:
  - name: cont1
    image: httpd
    env:
    - name: class
      value: "k8s"
    - name: username
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: user