apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    class: day2
spec:
  containers:
    - image: httpd
      name: cont1
      volumeMounts:
        - mountPath: /testData
          name: vol1
    - name: con2
      image: redis
      volumeMounts:
        - mountPath: /cont2Data
          name: vol1
  volumes:
    - name: vol1
      hostPath:
        path: /hostData
