apiVersion: v1
kind: Pod

metadata:
  name: pod1

spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: vol1
          mountPath: /abc
  volumes:
    - name: vol1
      nfs:
        server: 172.31.23.126
        path: /masterDataDir
